num1=float(input("enter the number of fresh loaves purchesed = "))
num2=float(input( "enter the number of old loaves purchesed =  "))
print("Regular price :Rs 185.00")
print("amout of news loaves  = "  ,185*num1)
print("amout of news old = ",74*num2)
print("Total amount = ", 185*num1 +74*num2)
